name: Get Releases

on:
  push:
    branches:
      - master
      - dev
      - 'op-version'
      - 'feature/*'
  pull_request:
      types: [closed]
  release:
      types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Get Releases
      id: get_releases
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/brenohenrike/skua/releases > releases.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: releases.json
        path: releases.json

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: ${{ github.head_ref }}
        commit_message: 'Automatic commit by GitHub Actions'
        files: 'releases.json'
        push: true
        push_options: '--force'

    - name: Delete artifact
      uses: geekyeggo/delete-artifact@v2
      with:
        name: releases.json
